### ISSUE TITLE
Questions about the comparison with BrainBERT.

### ISSUE THREAD

**Issue by NorbertZheng** [yzz673/Brant#2]
Hello! Thank you for this amazing work! I got some questions related to the results of BrainBERT when reading this work:
 - Do you get these results by directly finetuning BrainBERT with the pretrained weights (provided by Wang et al. 2023), or finetuning BrainBERT with the pretrained weights (after pretraining on your own sEEG dataset)?
 - Before doing classification tasks with BrainBERT, how are sEEG signals preprocessed? E.g., Laplacian reference.

Could you please offer the preprocessing code or describe the details? Many thanks:)

**Comment by NorbertZheng** [comment]
One more question about the pretraining, I see `bat_size=8` in your [Brant_src/pretrain/pre_train.py](https://github.com/yzz673/Brant/blob/e8a6133e30fd2f657f9b9599c0e42d223a5eeb2d/Brant_src/pretrain/pre_train.py#L85):
```python
dataloader = DataLoader(dataset, batch_size=bat_size, shuffle=False, drop_last=False)
```
So, in each pretraining batch, the input to the model is `(bat_size, ch_num, seq_len, seg_len)`, i.e., `(8, ch_num, 15, 1500)`. Is that correct? Considering you use data parallel on 8 GPUs, the total size of each batch is `8*8=64`?

We are trying to pretrain Brant on our data. I would appreciate it if you could provide some details about the pretraining process. Many thanks:)

**Comment by NorbertZheng** [comment]
One last question about the finetuning. I see `train_batch_size=4` & `infer_batch_size=4` in your [Brant_src/main.py](https://github.com/yzz673/Brant/blob/main/Brant_src/main.py):
```python
parser.add_argument("--train_batch_size", type=int, default=4)
parser.add_argument("--infer_batch_size", type=int, default=4)
```
So, considering classification task, in each finetuning & inference batch, the input to the model is `(bat_size, ch_num, seq_len, seg_len)`, i.e., `(4, ch_num, 15, 1500)`. Is that correct? And you only finetune the model on 1 GPU, the total size of each batch is exactly `4`?

Many thanks:)

**Comment by DaozeZhang** [comment]
> Hello! Thank you for this amazing work! I got some questions related to the results of BrainBERT when reading this work:
> 
> * Do you get these results by directly finetuning BrainBERT with the pretrained weights (provided by Wang et al. 2023), or finetuning BrainBERT with the pretrained weights (after pretraining on your own sEEG dataset)?
> * Before doing classification tasks with BrainBERT, how are sEEG signals preprocessed? E.g., Laplacian reference.
> 
> Could you please offer the preprocessing code or describe the details? Many thanks:)

Thank you for your recognition to our work. The results of BrainBERT are obtained by finetuning BrainBERT with the weights pretrained on our own dataset. Before using BrainBERT to perform the classification task, the preprocessing of the signal is explained in Section 3.1 of the paper and does not include Laplacian reference. The signal preprocessing code on the MAYO and FNUSA datasets is updated at `Brant/Brant_src/mayo_fnusa_preprocess.py`.

**Comment by DaozeZhang** [comment]
> One more question about the pretraining, I see `bat_size=8` in your [Brant_src/pretrain/pre_train.py](https://github.com/yzz673/Brant/blob/e8a6133e30fd2f657f9b9599c0e42d223a5eeb2d/Brant_src/pretrain/pre_train.py#L85):
> 
> ```python
> dataloader = DataLoader(dataset, batch_size=bat_size, shuffle=False, drop_last=False)
> ```
> 
> So, in each pretraining batch, the input to the model is `(bat_size, ch_num, seq_len, seg_len)`, i.e., `(8, ch_num, 15, 1500)`. Is that correct? Considering you use data parallel on 8 GPUs, the total size of each batch is `8*8=64`?
> 
> We are trying to pretrain Brant on our data. I would appreciate it if you could provide some details about the pretraining process. Many thanks:)

According to the Section 3.2 in the paper, during pretraining, the batch size is `16`. Therefore, the input to the model is `(16, ch_num, 15, 1500)`. The total batch size on 4 GPUs is `16*4=64`. The arguments in the code can be set according to your actual situation, such as Memory of your GPU.

**Comment by DaozeZhang** [comment]
> One last question about the finetuning. I see `train_batch_size=4` & `infer_batch_size=4` in your [Brant_src/main.py](https://github.com/yzz673/Brant/blob/main/Brant_src/main.py):
> 
> ```python
> parser.add_argument("--train_batch_size", type=int, default=4)
> parser.add_argument("--infer_batch_size", type=int, default=4)
> ```
> 
> So, considering classification task, in each finetuning & inference batch, the input to the model is `(bat_size, ch_num, seq_len, seg_len)`, i.e., `(4, ch_num, 15, 1500)`. Is that correct? And you only finetune the model on 1 GPU, the total size of each batch is exactly `4`?
> 
> Many thanks:)

Yes, this understanding is right, but usually these arguments are set according to the actual situation, such as Memory of your GPU.

**Comment by NorbertZheng** [comment]
Many thanks!
